### ISSUE TITLE
Uncaught TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by MavLeague** [jan00bl/mcfunction-novum#44]
[Enter steps to reproduce:]

1. type the command /function
2. ...

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: DESKTOP-LUKD1VE
**Thrown From**: [mcfunction-novum](https://github.com/jan00bl/mcfunction-novum) package 1.18.0

### Stack Trace

Uncaught TypeError: Cannot read property 'split' of undefined

```
At C:\Users\tilfa\.atom\packages\mcfunction-novum\lib\provider.js:266

TypeError: Cannot read property 'split' of undefined
    at getDatapackPath (/packages/mcfunction-novum/lib/provider.js:266:74)
    at getCustomEntries (/packages/mcfunction-novum/lib/provider.js:291:21)
    at suggestionList (/packages/mcfunction-novum/lib/provider.js:516:38)
    at suggestionList (/packages/mcfunction-novum/lib/provider.js:616:15)
    at Object.getSuggestions (/packages/mcfunction-novum/lib/provider.js:1009:10)
    at ~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:640887
    at Array.forEach (<anonymous>)
    at AutocompleteManager.getSuggestionsFromProviders (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:640403)
    at AutocompleteManager.findSuggestions (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:640141)
    at AutocompleteManager.requestNewSuggestions (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:648519)
    at AutocompleteManager.showOrHideSuggestionListForBufferChanges (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:649610)
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:1186925)
    at Emitter.emit (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:1188366)
    at TextBuffer.emitDidChangeTextEvent (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:507940)
    at TextBuffer.transact (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:495895)
    at TextEditor.transact (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:26664)
    at ~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:18599
    at TextEditor.mergeSelections (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:41933)
    at TextEditor.mergeIntersectingSelections (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:41487)
    at TextEditor.mutateSelectedText (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:18562)
    at TextEditor.insertText (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:18111)
    at TextEditor.e.<computed> [as insertText] (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:260300)
    at TextEditorComponent.didTextInput (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:96704)
```

### Commands

```
     -2:47.4.0 autocomplete-plus:confirm (input.hidden-input)
     -2:38.5.0 core:backspace (input.hidden-input)
  4x -2:37.5.0 core:move-right (input.hidden-input)
     -2:35.2.0 autocomplete-plus:confirm (input.hidden-input)
     -2:30.1.0 core:move-right (input.hidden-input)
     -2:22.1.0 autocomplete-plus:confirm (input.hidden-input)
  2x -1:56.9.0 core:backspace (input.hidden-input)
     -1:31.8.0 autocomplete-plus:confirm (input.hidden-input)
     -1:24.8.0 core:move-left (input.hidden-input)
     -1:24.2.0 core:move-right (input.hidden-input)
     -1:18.7.0 core:backspace (input.hidden-input)
     -1:16 autocomplete-plus:confirm (input.hidden-input)
  7x -1:05.6.0 core:move-left (input.hidden-input)
  7x -1:01.7.0 core:move-right (input.hidden-input)
     -0:56.6.0 core:paste (input.hidden-input)
  7x -0:52.9.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.18 
ftp-remote-edit 0.18.2 
mcfunction-novum 1.18.0 
teletype 0.13.4 
```

**Comment by jan00bl** [comment]
I cannot reproduce this.

Could you recreate the error and then press "ctrl + shift + i" and enter into the console:
atom.workspace.getActiveTextEditor().buffer.file

**Comment by Sertonix** [comment]
I think I found the reason. It seems to be caused by teletype, because there remote texteditor has no path.
https://github.com/atom/teletype/issues/228#issuecomment-346170001
The simeplest solution would be to change
https://github.com/jan00bl/mcfunction-novum/blob/9a7e3aafc1923eace4ef951233da487b61fecce8/lib/provider.js#L266
to
```js
const textEditor = atom.workspace.getActiveTextEditor();
if (textEditor.isRemote) return null;
let pathSplitted = textEditor.buffer.file.path.split(/[\\\/]/g);
```
