### ISSUE TITLE
Uncaught TypeError: Cannot read property 'noStop' of null

### ISSUE THREAD

**Issue by BrycesFailures** [jan00bl/mcfunction-novum#8]
The tp command causes a the TyperError when you type anything after it in the line

**Comment by jan00bl** [comment]
@BrycesFailures 
I cannot reproduce this bug by simply typing a tp command, could you provide me with more information such as the full stack trace?

**Comment by beSn0w** [comment]
![image](https://user-images.githubusercontent.com/62652411/89181375-df362d80-d593-11ea-8e0e-be9b4406cfb9.png)
I get this error whenever I press space (full stop) where my cursor is.
Hope this helps.

**Comment by beSn0w** [comment]
And the full stack trace: 

> TypeError: Cannot read property 'noStop' of null
    at Object.runCycle (C:\Users\Amanda\.atom\packages\mcfunction-novum\lib\provider.js:500:22)
    at Object.runCycle (C:\Users\Amanda\.atom\packages\mcfunction-novum\lib\provider.js:451:25)
    at Object.runCycle (C:\Users\Amanda\.atom\packages\mcfunction-novum\lib\provider.js:451:25)
    at Object.getCommandStop (C:\Users\Amanda\.atom\packages\mcfunction-novum\lib\provider.js:418:15)
    at Object.getSuggestions (C:\Users\Amanda\.atom\packages\mcfunction-novum\lib\provider.js:591:20)
    at C:\Users\Amanda\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:648882
    at Array.forEach (<anonymous>)
    at AutocompleteManager.getSuggestionsFromProviders (C:\Users\Amanda\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:648398)
    at AutocompleteManager.findSuggestions (C:\Users\Amanda\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:648136)
    at AutocompleteManager.requestNewSuggestions (C:\Users\Amanda\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:656669)
    at AutocompleteManager.showOrHideSuggestionListForBufferChanges (C:\Users\Amanda\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:657760)
    at Function.simpleDispatch (C:\Users\Amanda\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:1201500)
    at Emitter.emit (C:\Users\Amanda\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:1202941)
    at TextBuffer.emitDidChangeTextEvent (C:\Users\Amanda\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:505061)
    at TextBuffer.transact (C:\Users\Amanda\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:493171)
    at TextEditor.transact (C:\Users\Amanda\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:24215)
    at C:\Users\Amanda\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:16150
    at TextEditor.mergeSelections (C:\Users\Amanda\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:39484)
    at TextEditor.mergeIntersectingSelections (C:\Users\Amanda\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:39038)
    at TextEditor.mutateSelectedText (C:\Users\Amanda\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:16113)
    at TextEditor.insertText (C:\Users\Amanda\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:15662)
    at TextEditor.e.(anonymous function) [as insertText] (C:\Users\Amanda\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:258556)
    at TextEditorComponent.didTextInput (C:\Users\Amanda\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:94346)

**Comment by BrycesFailures** [comment]
Here's the full stack trace:

TypeError: Cannot read property 'noStop' of null
    at Object.runCycle (C:\Users\Bryke\.atom\packages\mcfunction-novum\lib\provider.js:500:22)
    at Object.runCycle (C:\Users\Bryke\.atom\packages\mcfunction-novum\lib\provider.js:451:25)
    at Object.runCycle (C:\Users\Bryke\.atom\packages\mcfunction-novum\lib\provider.js:451:25)
    at Object.runCycle (C:\Users\Bryke\.atom\packages\mcfunction-novum\lib\provider.js:451:25)
    at Object.getCommandStop (C:\Users\Bryke\.atom\packages\mcfunction-novum\lib\provider.js:418:15)
    at Object.getSuggestions (C:\Users\Bryke\.atom\packages\mcfunction-novum\lib\provider.js:591:20)
    at C:\Users\Bryke\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:648882
    at Array.forEach (<anonymous>)
    at AutocompleteManager.getSuggestionsFromProviders (C:\Users\Bryke\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:648398)
    at AutocompleteManager.findSuggestions (C:\Users\Bryke\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:648136)
    at AutocompleteManager.requestNewSuggestions (C:\Users\Bryke\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:656669)
    at AutocompleteManager.showOrHideSuggestionListForBufferChanges (C:\Users\Bryke\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:657760)
    at Function.simpleDispatch (C:\Users\Bryke\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:1201500)
    at Emitter.emit (C:\Users\Bryke\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:1202941)
    at TextBuffer.emitDidChangeTextEvent (C:\Users\Bryke\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:505061)
    at TextBuffer.transact (C:\Users\Bryke\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:493171)
    at TextEditor.transact (C:\Users\Bryke\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:24215)
    at C:\Users\Bryke\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:16150
    at TextEditor.mergeSelections (C:\Users\Bryke\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:39529)
    at TextEditor.mergeIntersectingSelections (C:\Users\Bryke\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:39038)
    at TextEditor.mutateSelectedText (C:\Users\Bryke\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:16113)
    at TextEditor.insertText (C:\Users\Bryke\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:15662)
    at TextEditor.e.(anonymous function) [as insertText] (C:\Users\Bryke\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:258556)
    at TextEditorComponent.didTextInput (C:\Users\Bryke\AppData\Local\atom\app-1.49.0\resources\app\static\<embedded>:11:94346)
